### ISSUE TITLE
Assert using Hex value

### ISSUE THREAD

**Issue by mauvesea** [vulcandth/pokecrystal16#12]
gfx/footprints.asm uses $100 for assert, instead of using a constant like NUM_POKEMON.

**Comment by aaaaaa123456789** [comment]
This is not a simple issue, because the codebase actually expects $100 as written, even though `NUM_POKEMON` is less than $100. Maybe the solution is to fix the code so there's no unused padding.

**Comment by Rangi42** [comment]
That should probably be done in pret as well:
```diff
 INCBIN "gfx/footprints/celebi.1bpp",     footprint_bottom
+
+	assert_table_length NUM_POKEMON
+
 INCBIN "gfx/footprints/252.1bpp",        footprint_bottom
-INCBIN "gfx/footprints/253.1bpp",        footprint_bottom
+INCBIN "gfx/footprints/253.1bpp",        footprint_bottom ; EGG
```

**Comment by Rangi42** [comment]
Yeah, fixing the [design flaw](https://github.com/pret/pokecrystal/blob/master/docs/design_flaws.md#footprints-are-split-into-top-and-bottom-halves) would be appropriate, like the many applied bugfixes which were relevant to the 16-bit features.

**Comment by vulcandth** [comment]
> Yeah, fixing the [design flaw](https://github.com/pret/pokecrystal/blob/master/docs/design_flaws.md#footprints-are-split-into-top-and-bottom-halves) would be appropriate, like the many applied bugfixes which were relevant to the 16-bit features.

That design flaw was already fixed in @aaaaaa123456789 's commit https://github.com/vulcandth/pokecrystal16/commit/03414e5b0f1af846cfd4168fb7f6ea7e4460f88b.

**Comment by Rangi42** [comment]
Great, then yes, the extra footprints are no longer necessary.

**Comment by vulcandth** [comment]
This has been resolved in the latest rebase.
