### ISSUE TITLE
Item expansion branches crash when a Pokemon evolves

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#17]
In the item expansion branches the ROM freezes on a white screen when a Pokemon evolves, see attached video. I can consistently reproduce with Caterpie on a clean repo clone. 

Similar behaviour occurred on an evolution line I altered (Ledyba was made to evolve at an earlier level and Ledia was given an evolution) but in this case instead of freezing on a white screen it reloads into the "This Game Pak is designed only for use on the Game Boy Color" error screen (didn't get a video of this though)

First occurred before today's commits but I was also able to reproduce after pulling them into my local repo.

**Reproduced in branches:**
expand-item-ID
item-newbox

**Device:**
Windows 11
Code compiled using Cygwin + RGBDS  0.7.0
Reproduced in Emulicious, BGB and mGBA

**Video:**
https://github.com/vulcandth/pokecrystal16/assets/156028124/6791c4c9-3b01-4802-9ddd-10cdcbf16d7c

(Also for future reference, which emulators are you concerned with re: bugs? Encountered a graphical issue that only occurs in Emulicious and not the other two I use)

**Comment by vulcandth** [comment]
My most trustworthy emulators are BGB and Sameboy. If it occurs in them, the it's likely a problem.. otherwise it's probably an emulator issue.

Either way.. thanks for the report!!!! I'll look into this ASAP. One question... You alluded to this only occurring recently from my latest rebase? Are you suggesting it was working before?

**Comment by MarioBones** [comment]
Sweet, I'll focus on running in BGB! 

Ah sorry, might not have been clear - it was occurring before the rebase too.

**Comment by vulcandth** [comment]
I found half of the problem; but In doing so I Identified another related problem.. Once I figure out the second part and finish my testing, I'll update the repo

**Comment by vulcandth** [comment]
Oh; I wanted to again thank you for reporting the problem. Those branches are marked experimental for a reason; but having people test and report problems goes a LONG way to getting the branches stable. I greatly appreciate the bug reports. Thanks again!

**Comment by vulcandth** [comment]
resolved in 7ff4931c199530bd78c10c823701283f6d4540bd

**Comment by MarioBones** [comment]
> Oh; I wanted to again thank you for reporting the problem. Those branches are marked experimental for a reason; but having people test and report problems goes a LONG way to getting the branches stable. I greatly appreciate the bug reports. Thanks again!

No problem, it's an exciting project! I'm still kinda stumbling my way around because I'm very new to Assembly, but it's cool learning how everything works

Confirming the fix works on my end :)
