### ISSUE TITLE
Catching Tutorial displays different Poke Balls in item expansion branches

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#18]
The Dude usually throws a regular Poke Ball in the catching tutorial, but in the item expansion branches he throws different kinds. In a clean item-newbox or expand-item-id branch he throws a Level Ball, and in my repo where I've made a bunch of additions and changes he throws a Park Ball. It doesn't stop the tutorial from completing though.

**Reproduced in branches:**
expand-item-id
item-newbox

**Video:**
![bgb64_fWZBR1vVD6](https://github.com/vulcandth/pokecrystal16/assets/156028124/bb4f7f96-010f-4610-a2e9-3386c04f5af7)

**Comment by vulcandth** [comment]
Thanks im looking into this, and should have a fix soon.

**Comment by vulcandth** [comment]
This is currently applied to the `expand-item-id` branch. It will be applied to `item-newbox` on the next rebase.
