### ISSUE TITLE
Unown all appear as the same letter form in PC

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#19]
Unown don't display as the proper letter in the PC. Their letter is saved correctly and will appear properly in battle and the stats menu, but when browsing the PC box they all appear as whichever Unown letter was last loaded.

Steps to reproduce:

1.  Catch multiple Unown letters
2.  Go to the PC
3.  Scroll across each Unown (they will all appear as the same letter)
4.  Load a different Unown front sprite by one of the following methods:

- Encounter an Unown in battle
- Load the Stats menu for an Unown
- Look at an Unown form in the Pokedex

6.  Return to the PC and scroll across each Unown (they will all appear as the last loaded Unown letter)

Reproduced in branches:
newbox
item-newbox
(Haven't checked others)

**Screenshots:**
Three different Unown letters have been caught:
<img width="240" alt="bgb64_cgIDZcifcD" src="https://github.com/vulcandth/pokecrystal16/assets/156028124/ab438370-687c-458e-a00d-f42246099a67">
But all appear as D in the PC:
<img width="240" alt="bgb64_K4yEwJHsrj" src="https://github.com/vulcandth/pokecrystal16/assets/156028124/e37af6db-a266-4b0a-a55d-0e4ad368ddab">
<img width="240" alt="bgb64_ZTbXVA5iwI" src="https://github.com/vulcandth/pokecrystal16/assets/156028124/c1a2cb45-542c-4294-94ea-361bc965f507">

**Comment by vulcandth** [comment]
Technically this isn't a bug. There is only one icon for Unown. If you want unique icons for each Unown you need to add them. I could add this, but it's a lower priority.

**Comment by MarioBones** [comment]
I was meaning the front sprite rather than the icon - these are Unowns D, A and C but they all show the frontsprite for D in the PC

**Comment by vulcandth** [comment]
Ah; thanks for the clarification. Yeah I think I know how to fix that. I'll post an update soon, probably this weekend.

**Comment by vulcandth** [comment]
Resolved in 5050465
