### ISSUE TITLE
Item expansion branches - NPC trades load data incorrectly

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#20]
When speaking to a trade NPC the details of their trades are incorrect. I've checked two trades so far - Kyle in Violet City speaks gibberish strings in place of Pokemon names, but Tim in Olivine City asks for the wrong Pokemon (and wants it to be female despite his trade not requiring a gender) and offers up a Krabby instead of Voltorb. Offering Tim a Krabby (the Pokemon he's supposed to ask for) returns the behaviour for offering him the wrong Pokemon.

Steps to reproduce:
1. Find a trade NPC e.g. Kyle in VioletKylesHouse
2. Speak to the trade NPC
3. Attempt to give them the appropriate Pokemon listed in data/events/npc_trades.asm

Observed in branches:
item-newbox
expand-item-id

Screenshots:
Kyle:
<img width="240" alt="bgb64_Lysr4Cc4q8" src="https://github.com/user-attachments/assets/048af71f-5831-4735-8925-6c84c063cb6c">
<img width="240" alt="bgb64_GXhUEBN4T0" src="https://github.com/user-attachments/assets/8bf7f7fa-9e68-413e-9d17-6aa8b37a9ea0">

Tim:
<img width="240" alt="bgb64_gPAoXoG3p6" src="https://github.com/user-attachments/assets/4f413cc3-a70d-43ec-855d-c8b2e60ae449">

**Comment by vulcandth** [comment]
resolved in 50e64d7dd9f55a7f78163a2eb0dc89d423ce3910
