### ISSUE TITLE
Item expansion branches - wrong Poke Ball withdrawn from PC

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#21]
When you withdraw Poke Balls from the player's PC the wrong ball type is withdrawn e.g. withdrawing a Poke Ball will give the player a Level Ball instead

Steps to reproduce:
1. Go to the PC in a Pokemon Center
2. Select the player's PC (the item storage PC)
3. Deposit a Poke Ball
4. Withdraw the Poke Ball

Observed in branches:
item-newbox
expand-item-id

Screenshots:
<img width="240" alt="bgb64_aUvGD4IPDa" src="https://github.com/user-attachments/assets/c2b98098-b871-4b60-a3bc-16ab86e1f8f2">

**Comment by vulcandth** [comment]
Thanks for the report! I'll address it soon.

**Comment by vulcandth** [comment]
Resolved in 3fd4d47
