### ISSUE TITLE
TM numbers not set properly for TMs 100 and over

### ISSUE THREAD

**Issue by MarioBones** [vulcandth/pokecrystal16#22]
TMs numbered 100 and over do not have their TM number display correctly in text. See screenshots of receiving TM100 (Giga Impact) and looking at it in the bag

<img width="240" alt="bgb64_7ulh4WmYBE" src="https://github.com/user-attachments/assets/fbef4e87-46b2-415e-bf1c-66ec8e9ffff6">
<img width="240" alt="bgb64_0ZGvH9f3Rw" src="https://github.com/user-attachments/assets/1b00993a-56b5-4495-9dff-80abc10a9736">

As per item_constants.asm I have not exceeded a combined total of 255 with the TMs and HMs (only 100 TMs plus 8 HMs, totalling 108)

**Affected branches:**
Have only tested this on item-newbox

**Steps to reproduce:**

1. In constants/item_constants.asm add enough TMs to the list so there are 100 or more values
2. Add the appropriate corresponding data to ItemTMAttributes in data/items/attributes.asm
3. Give the player a TM numbered 100 or higher using a verbosegiveitem event
4. Trigger the event in-game
5. Observe the TM name when received by the player
6. Open the bag and navigate to the TM/HM pocket
7. Observe the TM name in the list

**Comment by vulcandth** [comment]
This will likely not be fixed as it would require a UI redesign as their is not enough room for three characters.. this is similar to the Pokedex limit of 999 as there are not enough room for four characters.

**Comment by Rangi42** [comment]
If you want that many machine-learnable moves, make half of them Technical Records.

**Comment by MarioBones** [comment]
Thanks everyone! Wasn't sure whether this would be out-of-scope or not but figured I'd raise it just in case you weren't aware.

Love the Technical Record idea, might steal that.
