### ISSUE TITLE
PC16 Newbox unable to swap last mon

### ISSUE THREAD

**Issue by ElfinHilon10** [vulcandth/pokecrystal16#8]
When using swap mode with newbox, if you attempt to swap your last Pokemon with another Pokemon in your box, you're hit with an error saying it's your last healthy Pokemon, even though you're getting in another healthy mon.

**Comment by vulcandth** [comment]
Resolved in https://github.com/vulcandth/pokecrystal16/commit/3a3905631c2e05622c68a39973b13cedab359a9b
